# Generated by Django 3.0.3 on 2020-08-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('no_motor', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_h7', models.DateTimeField()),
                ('date_h3', models.DateTimeField()),
                ('date_phone', models.DateTimeField()),
                ('status_whatsapp', models.BooleanField(default=False)),
                ('status_kedatangan', models.BooleanField(default=False)),
                ('tipe_motor', models.CharField(max_length=200, null=True)),
                ('km_akhir', models.CharField(max_length=200, null=True)),
                ('ket', models.CharField(max_length=200, null=True)),
                ('status_call', models.BooleanField(default=False)),
            ],
        ),
    ]
