# Generated by Django 3.0.3 on 2020-08-26 14:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_h3',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 26, 14, 22, 4, 87197, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_h7',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 26, 14, 22, 4, 87150, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_phone',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 26, 14, 22, 4, 87232, tzinfo=utc)),
        ),
    ]
