# Generated by Django 3.0.3 on 2020-08-26 14:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20200826_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_h3',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 8, 26, 14, 23, 44, 553215, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_h7',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 8, 26, 14, 23, 44, 553171, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_phone',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 8, 26, 14, 23, 44, 553249, tzinfo=utc)),
        ),
    ]
