# Generated by Django 3.0.3 on 2020-08-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20200826_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status_h3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='status_h7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='status_telpon',
            field=models.BooleanField(default=False),
        ),
    ]
