# Generated by Django 3.0.3 on 2020-08-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='token_email',
        ),
        migrations.RemoveField(
            model_name='token',
            name='token_user',
        ),
    ]
