# Generated by Django 3.0.3 on 2020-09-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_sendwa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendwa',
            name='count',
        ),
        migrations.RemoveField(
            model_name='sendwa',
            name='message',
        ),
        migrations.RemoveField(
            model_name='sendwa',
            name='scheduled',
        ),
        migrations.RemoveField(
            model_name='sendwa',
            name='strdate',
        ),
        migrations.AddField(
            model_name='sendwa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sendwa',
            name='message1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sendwa',
            name='message2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sendwa',
            name='message3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sendwa',
            name='message4',
            field=models.TextField(blank=True),
        ),
    ]
