# Generated by Django 3.0.3 on 2020-09-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20200913_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='message1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='message2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='message3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='message4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='status_message1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='status_message2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='status_message3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='status_message4',
            field=models.BooleanField(default=False),
        ),
    ]
