# Generated by Django 3.0.3 on 2020-09-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20200913_0345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendwa',
            old_name='message1',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='sendwa',
            name='message2',
        ),
        migrations.RemoveField(
            model_name='sendwa',
            name='message3',
        ),
        migrations.RemoveField(
            model_name='sendwa',
            name='message4',
        ),
        migrations.AddField(
            model_name='sendwa',
            name='messages',
            field=models.CharField(choices=[('Message 1', 'Message 1'), ('Message 2', 'Message 2'), ('Message 3', 'Message 3'), ('Message 4', 'Message 4')], default='', max_length=200),
        ),
    ]
