# Generated by Django 3.0.3 on 2020-09-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20200913_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendwa',
            name='document',
        ),
        migrations.RemoveField(
            model_name='sendwa',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sendwa',
            name='type_message',
        ),
        migrations.AddField(
            model_name='sendwa',
            name='type_media_url',
            field=models.CharField(choices=[('Text Only', 'Text Only'), ('Image', 'Image'), ('Video', 'Video'), ('Document', 'Document')], default='', max_length=200),
        ),
    ]
