# Generated by Django 3.0.3 on 2020-09-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_auto_20200913_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='server_address',
            field=models.CharField(help_text='Only main name server address. Example: wa.test.com', max_length=200, null=True),
        ),
    ]
